### PR TITLE
Brining the latest changes in Hermes for RN69

### PR DESCRIPTION
**Pull request by mganandraj**
1. git merge hermes-2022-05-20-RNv0.69.0-ee8941b8874132b8f83e4486b63ed5c19fc3f111
2. Fixed a few compilation errors in our local forks, including the napi adapter
3. Switching to c++17 as is required now.
4. Tested interpreter and debugger. Found some issues in sampling profiler which is being investigated.

## Summary
git merge hermes-2022-05-20-RNv0.69.0-ee8941b8874132b8f83e4486b63ed5c19fc3f111

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/hermes-windows/pull/109)

### CODE REVIEW

**Comment by aeulitz** [comment]
Superseded by https://github.com/microsoft/hermes-windows/pull/118?

**Comment by jonthysell** [comment]
> Superseded by #118?

My guess is that since my last given the number of (no-op) commits that came from the merge in #124, this particular PR into main is no longer necessary. If the version of hermes-windows isn't working right on 0.69, then maybe there needs to be a separate 0.69 branch (snapped off prior to the 0.70 updates) and have these 0.69 merges done there.

**Comment by vmoroz** [comment]
I have created three branches to match RNW versions:
- rnw/0.70-stable
- rnw/0.69-stable
- rnw/0.68-stable

The rnw/0.69-stable should have all required code for 0.69 and probably renders this PR to be outdated.
@mganandraj please let me know if you have any questions.
There is an offline discussion about the branches for hermes-windows.
I plan to publish this information somewhere. Should we enable wiki for this repo?

**Comment by mganandraj** [comment]
> I have created three branches to match RNW versions:
> 
> * rnw/0.70-stable
> * rnw/0.69-stable
> * rnw/0.68-stable
> 
> The rnw/0.69-stable should have all required code for 0.69 and probably renders this PR to be outdated. @mganandraj please let me know if you have any questions. There is an offline discussion about the branches for hermes-windows. I plan to publish this information somewhere. Should we enable wiki for this repo?

@vmoroz This PR is no more required, as you suggested. Great to see the development on the branching story !

**Pull request closed without merging**
